# site settings
title: FrontMatter Templating
author: Morten Pradsgaard
description: "Awesome description [01]"
siteurl: https://cocap.github.io/FrontMatter/
baseurl: /FrontMatter/

# build settings
excerpt_separator: <!--more-->
port: 4000
markdown: markdownify
permalink: pretty
sass:
    style: compressed
