# site settings
title: FrontMatter Templating
author: Morten Pradsgaard
description: "Awesome description [01]"
siteurl: https://cocap.github.io/FrontMatter/
baseurl: https://cocap.github.io/FrontMatter/

# build settings
port: 4000
markdown: Kramdown
permalink: pretty
sass:
    style: compressed
